baseURL = 'http://example.org/'
languageCode = 'en-us'
title = "Kyle's Picks"
theme = "PaperMod"
[menu]
[[menu.main]]
  name = 'Home'
  url = '/'
  weight = 1
[[menu.main]]
  name = 'Picks'
  url = '/picks'
  weight = 2
