baseURL = 'https://kyles-picks.onrender.com/'
languageCode = 'en-us'
title = "Kyle's Picks"
theme = "PaperMod"
[menu]
[[menu.main]]
  name = 'Home'
  url = '/'
  weight = 1
[[menu.main]]
  name = 'Picks'
  url = '/categories/picks'
  weight = 2
[[menu.main]]
  name = 'Products'
  url = '/tags/'
  weight = 3 
